.SILENT:
PremierDossierUnix2019: Ecran.o main.o mainwindow.o moc_mainwindow.o
	echo Creation de PremierDossierUnix2019...
	g++ -m64 -Wl,-R,/opt/Qt4.8/lib -o PremierDossierUnix2019 main.o  mainwindow.o  moc_mainwindow.o Ecran.o   -L/usr/lib/64 -L/usr/X11/lib/64 -L/opt/Qt4.8/lib -lQtGui -L/opt/Qt4.8/lib -L/usr/lib/64 -L/usr/X11/lib/64 -lQtCore -lpthread -lrt

Ecran.o: Ecran.cpp
	echo Creation de Ecran.cpp ...
	g++ -DSUN -m64 -Wall Ecran.cpp -c

main.o: main.cpp
	echo Creation de main.o
	g++ -c -m64 -D_XOPEN_SOURCE=600 -D__EXTENSIONS__ -O2 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/opt/Qt4.8/mkspecs/solaris-g++-64 -I. -I/opt/Qt4.8/include/QtCore -I/opt/Qt4.8/include/QtGui -I/opt/Qt4.8/include -I/usr/include -I/usr/X11/include -o main.o main.cpp

mainwindow.o: mainwindow.cpp
	echo Creation de mainwindow.o ...
	g++ -c -m64 -D_XOPEN_SOURCE=600 -D__EXTENSIONS__ -O2 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/opt/Qt4.8/mkspecs/solaris-g++-64 -I. -I/opt/Qt4.8/include/QtCore -I/opt/Qt4.8/include/QtGui -I/opt/Qt4.8/include -I/usr/include -I/usr/X11/include -o mainwindow.o mainwindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp
	echo Creation de moc_mainwindow.o ...
	g++ -c -m64 -D_XOPEN_SOURCE=600 -D__EXTENSIONS__ -O2 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/opt/Qt4.8/mkspecs/solaris-g++-64 -I. -I/opt/Qt4.8/include/QtCore -I/opt/Qt4.8/include/QtGui -I/opt/Qt4.8/include -I/usr/include -I/usr/X11/include -o moc_mainwindow.o moc_mainwindow.cpp
